server:
  port: 8083

spring:
  application:
    name: "order-service"
  config:
#    import: "configserver:http://localhost:8888"
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:postgresql://localhost:5433/order-service
    username: root
    password: zoozoo

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

message:
  env: "dev environment"