server:
  port: 8084

spring:
  application:
    name: "Inventory-service"
    
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-service
    username: root
    password: zoozoo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false