server:
  port: 8081
spring:
  application:
    name: "ProductService"
  data:
    mongodb:
      uri: 'mongodb+srv://rijo:pass@productcluster.don7k.mongodb.net/product-service?retryWrites=true&w=majority&appName=productCluster'

message:
  env: "dev environment from config servber"