server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-service
    username: root
    password: zoozoo

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect