server:
  port: 8888
management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
spring:
  application:
    name: "configServer"

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
