#version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=zoozoo
      - POSTGRES_DB=authentication
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres
#  app:
#    depends_on:
#      - postgresdb
#    build:
#      context: .
#
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - 8081:8081
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:5432/authentication",
#        "spring.datasource.username" : "root",
#        "spring.datasource.password" : "zoozoo",
#        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
#        "spring.jpa.hibernate.ddl-auto" : "create"
#      }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true

volumes:
  db: